// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'FIREBASE_WEB_API_KEY',
    appId: '1:214944167158:web:452a3eaa74cc43c1b3e8d7',
    messagingSenderId: '214944167158',
    projectId: 'chatapp-e88ae',
    authDomain: 'chatapp-e88ae.firebaseapp.com',
    databaseURL: 'https://chatapp-e88ae-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-e88ae.firebasestorage.app',
    measurementId: 'G-6X6N9WK0ZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'FIREBASE_ANDROID_API_KEY',
    appId: '1:214944167158:android:2d5e31c015809cc1b3e8d7',
    messagingSenderId: '214944167158',
    projectId: 'chatapp-e88ae',
    databaseURL: 'https://chatapp-e88ae-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-e88ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'FIREBASE_IOS_API_KEY',
    appId: '1:214944167158:ios:f09ce0d02df39720b3e8d7',
    messagingSenderId: '214944167158',
    projectId: 'chatapp-e88ae',
    databaseURL: 'https://chatapp-e88ae-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-e88ae.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'FIREBASE_IOS_API_KEY',
    appId: '1:214944167158:ios:f09ce0d02df39720b3e8d7',
    messagingSenderId: '214944167158',
    projectId: 'chatapp-e88ae',
    databaseURL: 'https://chatapp-e88ae-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-e88ae.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'FIREBASE_WEB_API_KEY',
    appId: '1:214944167158:web:0191e83301dc25ddb3e8d7',
    messagingSenderId: '214944167158',
    projectId: 'chatapp-e88ae',
    authDomain: 'chatapp-e88ae.firebaseapp.com',
    databaseURL: 'https://chatapp-e88ae-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-e88ae.firebasestorage.app',
    measurementId: 'G-Y6G973J8J4',
  );
}
